### ISSUE TITLE
Installation instructions including jupyter

### ISSUE THREAD

**Issue by ewallace** [fish-quant/big-fish-examples#11]
Hello,
Thank you for a great package of code examples! This is really nice and enabled me to get started with big-fish immediately and understand how it works.

Jupyter notebooks are required, could `jupyter` be added to `requirements.txt`? Maybe with a helpful version?

It would help to flag the requirements in the package README.md as well.

Maybe a section saying. 
> First set up the `conda bigfish_env` as described in big-fish installation instructions.
> Then activate the environment and install jupyter:

```
conda activate bigfish_env
conda install jupyter
```

> Then to run these notebooks, start with
```
jupyter notebook
```

This is mostly for beginners - someone who has only just done a fresh big-fish installation in a new conda environment won't have the jupyter notebook or tensorflow installed.

I had some separate issues around tensorflow versions that I'll put in a separate issue ticket.

Thanks again!
Edward

**Comment by Henley13** [comment]
Hello @ewallace,

I am not in favor to add jupyter in the requirements because I would prefer keep it minimalist. Jupyter is not needed to run big-fish. However I should mention it more explicitly in the documentation and in the readme of the examples repository.

**Comment by ewallace** [comment]
Thank you, this is really clear documentation and much appreciated.
