### ISSUE TITLE
5 - Detect spots.ipynb wrong input parameter for local max detection

### ISSUE THREAD

**Issue by muellerflorian** [fish-quant/big-fish-examples#2]
In this example, the loca_maximum_detection does not have the correct input parameters  (it still uses an older version)

currently it is using `sigma`
```
mask = detection.local_maximum_detection(rna_log, sigma)
``` 

while it should use `min_distance`
```
mask = detection.local_maximum_detection(rna_log, min_distance)

**Comment by Henley13** [comment]
Done !
The code is good, I just explicitly add the name of the parameter. Good for you ?

**Comment by muellerflorian** [comment]
ok. got it.
