### ISSUE TITLE
6 - Extract cell level results.ipynb: use cell_id rather than generic index

### ISSUE THREAD

**Issue by muellerflorian** [fish-quant/big-fish-examples#3]
In the section "To visualize the results of your extraction ...", a loop  over the results for each cell is performed. Each cell is then identified with a generic running index `i`. However, it might be better to directly use the index of the cell as defined by the segmentation results (`cell_results["cell_id"]`). Like this a direct link between the plots (that are generated for each cell, and the segmentation is established).

**Comment by Henley13** [comment]
Done with the last release. I close the issue.
