### ISSUE TITLE
6 - Extract cell level results.ipynb: rename output parameter after ts composition

### ISSUE THREAD

**Issue by muellerflorian** [fish-quant/big-fish-examples#4]
When calling transcription sites with the line:

```
spots_no_ts, foci, ts = stack.remove_transcription_site(spots, foci, nuc_label, ndim=3)
```

The original array `foci` is overwritten and replaced with the array not containing transcription sites. when this line is now called again, not transcription sites are detected. Replacing the output argument `foci` by 'foci_no_ts` (as done for the spots), would resolve this issue.

**Comment by Henley13** [comment]
I use `spots_no_ts, foci, ts = multistack.remove_transcription_site(spots, clusters, nuc_label, ndim=3)` now!

Thanks for the issue.
