### ISSUE TITLE
How to calculate PSF parameters?

### ISSUE THREAD

**Issue by dakota-hawkins** [fish-quant/big-fish-examples#7]
Hi there!

Thanks for the great package -- I've been playing around with it for some new smFISH data, and it's been really great and intuitive so far. One question I had, is if you could provide any information on the best way to calculate `psf_z` and `psf_yx` from microscope metadata files?

While I've done some experience in image analysis, point spread functions are new to me, so any guidance would be greatly appreciated!

Thanks,

Dakota

**Comment by muellerflorian** [comment]
Hi Dakota,

this corresponds to the size of the point-spread-function (PSF). Essentially, the size of an object smaller than the resolution limit of the microscope. we use this to set a few parameters, e.g. the size of the filters, in the background. 

one fast way to get it (roughly), is to open one of your FISH images and you simply visually check how "wide" your spots are in xy and z, the sigma is roughly half of their width. on a standard widefield system, this will be around 200nm in xy, and 500nm in z. 

hope this helps!

best
Florian

**Comment by dakota-hawkins** [comment]
Thanks so much! Appreciate your insight on this. Very much appreciate the reply + the library itself!

**Comment by muellerflorian** [comment]
with pleasure!
