### ISSUE TITLE
Difference between PSF and voxel_size

### ISSUE THREAD

**Issue by luisub** [fish-quant/big-fish-examples#8]
Hi Arthur and  Prof. Mueller,

I hope you are doing well. I have been using big-FISH and I want to make sure that I understand the parameters I need to pass for the segmentation process. Specifically, I am not sure what is the _difference between a **PSF** and **voxel_size**_. I understand that I need to measure and quantify the PSF in my microscope, but I am not sure what is the voxel_size? 

According to your [documentation](https://big-fish.readthedocs.io/en/stable/detection/spots.html) you define:

"voxel_size_z int or float or None
   Height of a voxel, along the z axis, in nanometer. If None, image is considered in 2-d.

psf_z int or float or None
   Theoretical size of the PSF emitted by a spot in the z plan, in nanometer. If None, image is considered in 2-d."

Is the voxel_size the size (xy, and z) for the average mRNA spot I am trying to detect? and if this is the case, how do you determine this number in your example [notebook](https://github.com/fish-quant/big-fish-examples/blob/master/notebooks/5%20-%20Detect%20spots.ipynb) ? 

Thanks a lot for putting together this software.

Best,

Luis

**Comment by muellerflorian** [comment]
Hey Luis, 

the **voxel-size** describes the dimensions of the pixels in your image. In XY they are determined by the size of the camera-chip and the objective your are using. In Z,  it is the step-size you defined when taking your images. 

The **PSF values** describe the typical size of your RNA. An RNA is smaller then the optical resolution of a typical microscope, and on the microscope you will see it as a Point-Spread-Function. The size of the Point-spread function depends on a number of parameters, including your microscope type, the objective you are using and also the fluorophore. 

In practice, you can should visually inspect your spot-size and provide this value (for a typical widefield microscope it will be around 200nm in XY, and 500 nm in Z).

**Comment by muellerflorian** [comment]
see also https://github.com/fish-quant/big-fish/issues/55

@Henley13 . We now got 3 issues with a question related to PSF vs Voxel size. I think we should describe this more clearly.

**Comment by Henley13** [comment]
As we reword the `psf` parameters and clarify the docstring throughout the package (big-fish >= 0.6.0), I'll close this issue. Now we have `object_radius` (instead of `psf`) and `voxel_size` as input parameters.
