### ISSUE TITLE
Notebook dtype issue with skimage latest version

### ISSUE THREAD

**Issue by 15bonte** [fish-quant/big-fish-examples#9]
Running cell 5 of notebook "Segment nuclei and cells.ipynb" crashes because in cell 4 segmentation.label_instances returns int32 array instead of int64 as indicated in the documentation, and plot.plot_segmentation cannot handle this type.

scikit-image version is 0.19.2

**Comment by muellerflorian** [comment]
thanks for reporting this. looks like this [big-fish issue 67](https://github.com/fish-quant/big-fish/issues/67).

@Henley13, is there a way to make the type checking less stringent?

**Comment by muellerflorian** [comment]
Hello @15bonte ,

hopefully the latest version of big-fish (0.6.2) should resolve this issue. could you please check if that's the case.

**Comment by 15bonte** [comment]
Hello @muellerflorian,

Sorry for the very late answer, I had completely forgotten this issue.

You were right, upgrading to 0.6.2 resolved the problem, everything works fine. Thank you very much!
